name: CI
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo $HOME
        
      - name: 'Create env file'
        run: |
          echo "${{ secrets.ENV }}" > .env; cat .env 
